# Generated by Django 5.0.3 on 2024-04-16 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keshoapp', '0002_payment_attendees_b_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='paycurrency',
            field=models.CharField(blank=True, default='UGX', max_length=10, null=True),
        ),
    ]
