# Generated by Django 5.0.3 on 2024-04-18 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keshoapp', '0003_alter_payment_paycurrency'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Attendees',
            new_name='Attendee',
        ),
    ]
