# Generated by Django 5.0.3 on 2024-04-19 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keshoapp', '0004_rename_attendees_attendee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendee',
            name='b_fee',
        ),
        migrations.AddField(
            model_name='payment',
            name='b_fee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='keshoapp.attendee'),
        ),
    ]
